# See config.example.yml for documentation.
object_base: orig/RS9E8P_PROTO
object: sys/main.dol
hash: 3d7b7a5526ed30bb00757088c0b58297a58a655a
symbols: config/RS9E8P_PROTO/symbols.txt
splits: config/RS9E8P_PROTO/splits.txt
# Change this to match the linker version.
# See config.example.yml for a list.
mw_comment_version: 11
